### ISSUE TITLE
Getting content for URL redirection not working

### ISSUE THREAD

**Issue by s26** [LeonardoCardoso/Link-Preview#12]
Hi Leonardo,

Great project.

I have used your code in my project.

I am facing issue with url redirection. Not able to get title,description... for url having 301,302 status code.

I have also tried to update curl options in your LinkPreview -> getPage function. But not able to get content.

Can you please tell me how should I solve above issue?

Thanks in advance.

**Comment by LeonardoCardoso** [comment]
Duplicate #3
