### ISSUE TITLE
Is there a way to remove preview before posting when not needed?

### ISSUE THREAD

**Issue by leoc1f3r** [LeonardoCardoso/Link-Preview#14]

**Comment by LeonardoCardoso** [comment]
Yes, just click on **cancel button**. 

![screen shot 2016-07-28 at 07 48 32](https://cloud.githubusercontent.com/assets/1775157/17210222/b653a6d0-5497-11e6-95dc-4389ed8b934f.png)
![screen shot 2016-07-28 at 07 48 35](https://cloud.githubusercontent.com/assets/1775157/17210223/b667d4a2-5497-11e6-8341-46ac06518b9c.png)
![screen shot 2016-07-28 at 07 48 38](https://cloud.githubusercontent.com/assets/1775157/17210224/b67667e2-5497-11e6-9e63-9743224e2533.png)
